image: atlassian/default-image:2

pipelines:
  branches:
    master:
      - step:
          deployment: test
          name: Deploy service
          caches:
            - node
          script:
            - cd svc
            - cat env_template.json | sed "s:MASTER_DB_HOST:$MASTER_DB_HOST_TRIAL:g" | sed "s:MASTER_DB_USER:$MASTER_DB_USER_TRIAL:g" | sed "s:MASTER_DB_PASSWORD:$MASTER_DB_PASSWORD_TRIAL:g" | sed "s:MASTER_DB:$MASTER_DB_TRIAL:g" > env.json
            - cat env.json
            - npm install
            # temporary disable test run
            #- npm test
            - zip -r api.zip .
            - ls
            - pipe: atlassian/aws-elasticbeanstalk-deploy:0.2.9
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                APPLICATION_NAME: $ACME_APPLICATION_NAME
                ENVIRONMENT_NAME: $ACME_ENVIRONMENT_NAME_TRIAL
                ZIP_FILE: $ZIP_FILE
                S3_BUCKET: $S3_NODE_BUCKET
  custom:
    deploy-to-prod-acme:
      - step:
          name: Deploy service
          caches:
            - node
          script:
            - cd svc
            - cat env_template.json | sed "s:MASTER_DB_HOST:$MASTER_DB_HOST_PROD:g" | sed "s:MASTER_DB_USER:$MASTER_DB_USER_PROD:g" | sed "s:MASTER_DB_PASSWORD:$MASTER_DB_PASSWORD_PROD:g" | sed "s:MASTER_DB:$MASTER_DB_PROD:g" > env.json
            - cat env.json
            - npm install
            # temporary disable test run
            #- npm test
            - zip -r api.zip .
            - ls
            - pipe: atlassian/aws-elasticbeanstalk-deploy:0.2.9
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                APPLICATION_NAME: $ACME_APPLICATION_NAME
                ENVIRONMENT_NAME: $ACME_ENVIRONMENT_NAME_PROD
                ZIP_FILE: $ZIP_FILE
                S3_BUCKET: $S3_NODE_BUCKET