module.exports = {
    "up": "CREATE TABLE `sp_staffplan`.`CUSTOM_LABEL` ( `ID` INT NOT NULL AUTO_INCREMENT , `TABLE_NAME` VARCHAR(50) NOT NULL , `FIELD_NAME` VARCHAR(50) NOT NULL , `CUSTOM_FIELD` VARCHAR(50) NOT NULL , PRIMARY KEY (`ID`)) ENGINE = InnoDB;",
    "down": ""
}