module.exports = {
    "up": "CREATE TABLE SUBSCRIBER(ID INT NOT NULL AUTO_INCREMENT, UNIQUE KEY ID (ID), NAME varchar(255), CONTACT_NUMBER varchar(255), SUBSCRIPTION_ID INT NOT NULL,FOREIGN KEY (`SUBSCRIPTION_ID`) REFERENCES `SUBSCRIPTION` (`ID`))",
    "down": ""
}