// const CONST = require('../../common/const');

module.exports = {
  ProjectList: () => (
    `SELECT 
      PROJECT.PROJECT_NAME, 
      PROJECT.PROJECT_CITY,
      PROJECT.PROJECT_STATE,
      PROJECT_STATUS.STATUS_NAME,
      PROJECT.START_DATE,
      PROJECT.END_DATE,
      PROJECT.PROJECT_ROM,
      OFFICE.OFFICE_NAME,
      (SELECT COUNT(NOTE_ID) FROM
        NOTES WHERE NOTES.PROJECT_ID = PROJECT.PROJECT_ID) NOTECOUNT,
      (SELECT COUNT(ID) FROM
        PLANNED_PROJECT_STAFF WHERE
          PLANNED_PROJECT_STAFF.PROJECT_ID = PROJECT.PROJECT_ID) OPENROLE
    FROM 
      PROJECT
    INNER JOIN 
      PROJECT_STATUS
        ON PROJECT_STATUS_ID = PROJECT_STATUS.STATUS_ID
    INNER JOIN 
      OFFICE
        ON OFFICE.OFFICE_ID = PROJECT.OFFICE_ID
        `
  ),
  getTeam: (id) => (
    `
    SELECT
      PROJECT_STAFF.PROJECT_ID,
      STAFF.STAFF_ID,
      STAFF.FIRST_NAME,
      STAFF_ROLE.ROLE_NAME
    FROM 
      PROJECT_STAFF  
    INNER JOIN STAFF  
      ON PROJECT_STAFF.STAFF_ID = STAFF.STAFF_ID
    INNER JOIN STAFF_ROLE
      ON STAFF_ROLE.ROLE_ID = PROJECT_STAFF.PROJECT_ROLE_ID

    WHERE
      PROJECT_STAFF.PROJECT_ID = ${id}
    `
  )
}