
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


# Dump of table COMPANY
# ------------------------------------------------------------

DROP TABLE IF EXISTS `COMPANY`;

CREATE TABLE `COMPANY` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL DEFAULT '',
  `ADDRESS` varchar(255) NOT NULL DEFAULT '',
  `PRIMARY_CONTACT` varchar(155) NOT NULL DEFAULT '',
  `PRIMARY_CONTACT_EMAIL` varchar(255) NOT NULL DEFAULT '',
  `PRIMARY_CONTACT_PHONE` varchar(155) NOT NULL DEFAULT '',
  `PRIMARY_CONTACT_TITLE` varchar(255) NOT NULL DEFAULT '',
  `CREATED_DATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_DATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATED_BY` varchar(255) NOT NULL DEFAULT '',
  `UPDATED_BY` varchar(255) NOT NULL DEFAULT '',
  `COMPANY_DB` varchar(255) NOT NULL DEFAULT '',
  `DOMAIN` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


# Dump of table ENVIRONMENT_TYPE
# ------------------------------------------------------------

DROP TABLE IF EXISTS `ENVIRONMENT_TYPE`;

CREATE TABLE `ENVIRONMENT_TYPE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  `DETAILS` varchar(255) NOT NULL DEFAULT '',
  `CREATED_DATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_DATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATED_BY` varchar(255) NOT NULL DEFAULT '',
  `UPDATED_BY` varchar(255) NOT NULL DEFAULT '',
  `SUBDOMAIN` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


# Dump of table COMPANY_ENVIRONMENT
# ------------------------------------------------------------

DROP TABLE IF EXISTS `COMPANY_ENVIRONMENT`;

CREATE TABLE `COMPANY_ENVIRONMENT` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `COMPANY_ID` int(11) NOT NULL,
  `ENVIRONMENT_TYPE_ID` int(11) NOT NULL,
  `STATUS` varchar(255) NOT NULL DEFAULT '',
  `START_DATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATED_DATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_DATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATED_BY` varchar(255) NOT NULL DEFAULT '',
  `UPDATED_BY` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`ID`),
  FOREIGN KEY (`COMPANY_ID`) REFERENCES `COMPANY` (`ID`),
  FOREIGN KEY (`ENVIRONMENT_TYPE_ID`) REFERENCES `ENVIRONMENT_TYPE` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



# Dump of table SUBSCRIPTION_TYPE
# ------------------------------------------------------------

DROP TABLE IF EXISTS `SUBSCRIPTION_TYPE`;

CREATE TABLE `SUBSCRIPTION_TYPE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL DEFAULT '',
  `DETAILS` varchar(255) NOT NULL DEFAULT '',
  `LIST_PRICE_PER_MONTH` decimal(15,2) NOT NULL,
  `LIST_PRICE_ANNUAL` decimal(15,2) NOT NULL,
  `SUPPORT_FEES_ANNUAL` decimal(15,2) NOT NULL,
  `STAGING_SERVICE_FEE` decimal(15,2) NOT NULL,
  `CREATED_DATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_DATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATED_BY` varchar(255) NOT NULL DEFAULT '',
  `UPDATED_BY` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


# Dump of table SUBSCRIPTION_SERVICE
# ------------------------------------------------------------

DROP TABLE IF EXISTS `SUBSCRIPTION_SERVICE`;

CREATE TABLE `SUBSCRIPTION_SERVICE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `COMPANY_ID` int(11) NOT NULL,
  `SUBSCRIPTION_TYPE_ID` int(11) NOT NULL,
  `USER_COUNT` int(11) NOT NULL,
  `REMAINING_USER_COUNT` int(11) NOT NULL,
  `CREATED_DATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_DATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATED_BY` varchar(255) NOT NULL DEFAULT '',
  `UPDATED_BY` varchar(255) NOT NULL DEFAULT '',
  `ACTUAL_MONTHLY_FEE` decimal(15,2) NOT NULL,
  `ACTUAL_ANNUAL_FEE` decimal(15,2) NOT NULL,
  `ACTUAL_SUPPORT_FEE` decimal(15,2) NOT NULL,
  PRIMARY KEY (`ID`),
  FOREIGN KEY (`COMPANY_ID`) REFERENCES `COMPANY` (`ID`),
  FOREIGN KEY (`SUBSCRIPTION_TYPE_ID`) REFERENCES `SUBSCRIPTION_TYPE` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;