/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


# Dump of table COMPANY
# ------------------------------------------------------------

DROP TABLE IF EXISTS `COMPANY`;

CREATE TABLE `COMPANY` (
  `COMPANY_ID` int(11) NOT NULL AUTO_INCREMENT,
  `COMPANY_NAME` varchar(255) NOT NULL,
  `COMPANY_ADDRESS` varchar(255) NOT NULL,
  `PRIMARY_CONTACT` varchar(155) NOT NULL,
  `PRIMARY_CONTACT_EMAIL` varchar(255) NOT NULL,
  `PRIMARY_CONTACT_TEL_NUMBER` varchar(155) NOT NULL,
  `PRIMARY_CONTACT_TITLE` varchar(255) NOT NULL,
  `CREATED_DATE_TIME` datetime NOT NULL,
  `UPDATED_DATE_TIME` datetime NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `UPDATED_BY` int(11) NOT NULL,
  `COMPANY_DB` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`COMPANY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


# Dump of table SUBSCRIBER
# ------------------------------------------------------------

DROP TABLE IF EXISTS `SUBSCRIBER`;

CREATE TABLE `SUBSCRIBER` (
  `SUBSCRIBER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `COMPANY_ID` int(11) NOT NULL,
  `CREATED_DATE` datetime NOT NULL,
  `CREATED_BY_USER` int(11) NOT NULL,
  `DOMAIN_ID` varchar(255) NOT NULL,
  PRIMARY KEY (`SUBSCRIBER_ID`),
  KEY `COMPANY_ID` (`COMPANY_ID`),
  CONSTRAINT `COMPANY_ID` FOREIGN KEY (`COMPANY_ID`) REFERENCES `COMPANY` (`COMPANY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


# Dump of table SUBSCRIPTION_SERVICE
# ------------------------------------------------------------

DROP TABLE IF EXISTS `SUBSCRIPTION_SERVICE`;

CREATE TABLE `SUBSCRIPTION_SERVICE` (
  `SUBSCRIPTION_SERVICE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `SUBSCRIBER_ID` int(11) NOT NULL,
  `SUBSCRIPTION_TYPE_ID` int(11) NOT NULL,
  `COUNT` int(11) NOT NULL,
  `CREATED_DATE_TIME` datetime NOT NULL,
  `UPDATED_DATE_TIME` datetime NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `UPDATED_BY` int(11) NOT NULL,
  PRIMARY KEY (`SUBSCRIPTION_SERVICE_ID`),
  KEY `SUBSCRIBER_ID` (`SUBSCRIBER_ID`),
  CONSTRAINT `SUBSCRIBER_ID` FOREIGN KEY (`SUBSCRIBER_ID`) REFERENCES `SUBSCRIBER` (`SUBSCRIBER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


# Dump of table SUBSCRIPTION_TYPE
# ------------------------------------------------------------

DROP TABLE IF EXISTS `SUBSCRIPTION_TYPE`;

CREATE TABLE `SUBSCRIPTION_TYPE` (
  `SUBSCRIPTION_TYPE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `SUBSCRIPTION_NAME` varchar(255) NOT NULL,
  `SUBSCRIPTION_DETAILS` varchar(255) NOT NULL,
  `SUBSCRIPTION_PRICING_PER_MONTH` varchar(255) NOT NULL,
  `CREATED_DATE_TIME` datetime NOT NULL,
  `UPDATED_DATE_TIME` datetime NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `UPDATED_BY` int(11) NOT NULL,
  PRIMARY KEY (`SUBSCRIPTION_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


# Dump of table TENANT_DETAILS
# ------------------------------------------------------------

DROP TABLE IF EXISTS `TENANT_DETAILS`;

CREATE TABLE `TENANT_DETAILS` (
  `TENANT_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `SUBSCRIBER_ID` int(11) NOT NULL,
  `TENANT_TYPE_ID` int(11) NOT NULL,
  `START_DATE` date NOT NULL,
  `DOMAIN_ID` varchar(255) NOT NULL,
  `TENANT_STATUS` varchar(155) NOT NULL,
  PRIMARY KEY (`TENANT_ID`),
  KEY `SUBSCRIBER_ID` (`SUBSCRIBER_ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

# Dump of table TENANT_TYPE
# ------------------------------------------------------------

DROP TABLE IF EXISTS `TENANT_TYPE`;

CREATE TABLE `TENANT_TYPE` (
  `TENANT_TYPE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TENANT_DESCRIPTION` varchar(255) NOT NULL,
  `UPDATED_BY` int(11) NOT NULL,
  PRIMARY KEY (`TENANT_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
