/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


# Dump of table ACCESS_TYPE
# ------------------------------------------------------------

DROP TABLE IF EXISTS `ACCESS_TYPE`;

CREATE TABLE `ACCESS_TYPE` (
  `ID` int(11) NOT NULL,
  `TYPE` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



# Dump of table ACCESS_TYPE_COMBINATION
# ------------------------------------------------------------

DROP TABLE IF EXISTS `ACCESS_TYPE_COMBINATION`;

CREATE TABLE `ACCESS_TYPE_COMBINATION` (
  `ID` int(11) NOT NULL,
  `COMBINATION` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



# Dump of table CATEGORY
# ------------------------------------------------------------

DROP TABLE IF EXISTS `CATEGORY`;

CREATE TABLE `CATEGORY` (
  `CATEGORY_ID` int(10) NOT NULL,
  `CATEGORY_NAME` varchar(255) NOT NULL,
  PRIMARY KEY (`CATEGORY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



# Dump of table CERTIFICATION_SKILLS
# ------------------------------------------------------------

DROP TABLE IF EXISTS `CERTIFICATION_SKILLS`;

CREATE TABLE `CERTIFICATION_SKILLS` (
  `CERTIFICATION_ID` int(11) NOT NULL,
  `CERTIFICATION_NAME` varchar(255) NOT NULL,
  PRIMARY KEY (`CERTIFICATION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



# Dump of table CUSTOM_LABEL
# ------------------------------------------------------------

DROP TABLE IF EXISTS `CUSTOM_LABEL`;

CREATE TABLE `CUSTOM_LABEL` (
  `ID` int(11) NOT NULL,
  `TABLE_NAME` varchar(50) NOT NULL,
  `FIELD_NAME` varchar(50) NOT NULL,
  `CUSTOM_FIELD` varchar(50) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



# Dump of table CUSTOMER
# ------------------------------------------------------------

DROP TABLE IF EXISTS `CUSTOMER`;

CREATE TABLE `CUSTOMER` (
  `CUSTOMER_ID` varchar(50) NOT NULL,
  `CUSTOMER_NAME` varchar(255) DEFAULT NULL,
  `CUSTOMER_ADDRESS` varchar(255) DEFAULT NULL,
  `CUSTOMER_CITY` varchar(255) DEFAULT NULL,
  `CUSTOMER_STATE` varchar(10) DEFAULT NULL,
  `CUSTOMER_ZIP` varchar(10) DEFAULT NULL,
  `CUSTOMER_CONTACT` varchar(255) DEFAULT NULL,
  `CONTACT_PHONE` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`CUSTOMER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



# Dump of table CUSTOMER_PROJECTS
# ------------------------------------------------------------

DROP TABLE IF EXISTS `CUSTOMER_PROJECTS`;

CREATE TABLE `CUSTOMER_PROJECTS` (
  `PROJECT_ID` varchar(255) NOT NULL,
  `CUSTOMER_ID` varchar(255) NOT NULL,
  PRIMARY KEY (`PROJECT_ID`,`CUSTOMER_ID`),
  KEY `FK_CUSTOMER` (`CUSTOMER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



# Dump of table OFFICE
# ------------------------------------------------------------

DROP TABLE IF EXISTS `OFFICE`;

CREATE TABLE `OFFICE` (
  `OFFICE_ID` varchar(255) NOT NULL,
  `OFFICE_NAME` varchar(255) DEFAULT NULL,
  `OFFICE_ADDRESS` varchar(255) DEFAULT NULL,
  `OFFICE_CITY` varchar(255) NOT NULL,
  `OFFICE_STATE` varchar(10) DEFAULT NULL,
  `OFFICE_ZIP` varchar(10) DEFAULT NULL,
  `OFFICE_TYPE` varchar(50) DEFAULT NULL,
  `REGION_ID` int(10) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



# Dump of table PLANNED_PROJECT_PEOPLE
# ------------------------------------------------------------

DROP TABLE IF EXISTS `PLANNED_PROJECT_PEOPLE`;

CREATE TABLE `PLANNED_PROJECT_PEOPLE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PROJECT_ID` varchar(40) NOT NULL,
  `START_DATE` date NOT NULL,
  `END_DATE` date NOT NULL,
  `ALLOCATION` float(8,2) NOT NULL,
  `PROJECT_ROLE_ID` int(10) NOT NULL,
  `ASSIGNMENT_DURATION` int(10) DEFAULT NULL,
  `CONFIRMED` tinyint(1) DEFAULT NULL,
  `NEXT_AVAILABLE` date DEFAULT NULL,
  `RESUME_SUBMITTED` enum('0','1') NOT NULL DEFAULT '0' COMMENT '0: false , 1: true',
  KEY `ID` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



# Dump of table PROJECT
# ------------------------------------------------------------

DROP TABLE IF EXISTS `PROJECT`;

CREATE TABLE `PROJECT` (
  `PROJECT_ID` varchar(255) NOT NULL,
  `GROUP_ID` int(11) NOT NULL,
  `PROJECT_NO` varchar(255) NOT NULL,
  `PROJECT_NAME` varchar(255) NOT NULL,
  `PROJECT_ROM` varchar(20) DEFAULT NULL,
  `PROJECT_ADDRESS` varchar(255) DEFAULT NULL,
  `PROJECT_CITY` varchar(255) DEFAULT NULL,
  `PROJECT_STATE` varchar(255) DEFAULT NULL,
  `PROJECT_ZIP` varchar(10) DEFAULT NULL,
  `START_DATE` date DEFAULT NULL,
  `END_DATE` date DEFAULT NULL,
  `PROJECT_DURATION` int(10) DEFAULT NULL,
  `PROJECT_STATUS_ID` int(10) DEFAULT NULL,
  `PROJECT_TYPE_ID` int(10) DEFAULT NULL,
  `OFFICE_ID` varchar(255) DEFAULT NULL,
  `CATEGORY_ID` int(11) NOT NULL,
  `PROJECT_DESCRIPTION` text,
  `TIMELINE_TYPE` enum('1','2') DEFAULT NULL COMMENT '"1": "Estimated" , "2":"Confirmed"'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



# Dump of table PROJECT_GROUP
# ------------------------------------------------------------

DROP TABLE IF EXISTS `PROJECT_GROUP`;

CREATE TABLE `PROJECT_GROUP` (
  `GROUP_ID` int(11) NOT NULL,
  `GROUP_NAME` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



# Dump of table PROJECT_PEOPLE
# ------------------------------------------------------------

DROP TABLE IF EXISTS `PROJECT_PEOPLE`;

CREATE TABLE `PROJECT_PEOPLE` (
  `STAFF_ID` varchar(255) NOT NULL,
  `PROJECT_ID` varchar(40) DEFAULT NULL,
  `START_DATE` date DEFAULT NULL,
  `END_DATE` date DEFAULT NULL,
  `ALLOCATION` float(8,2) DEFAULT NULL,
  `PROJECT_ROLE_ID` int(10) DEFAULT NULL,
  `ASSIGNMENT_DURATION` int(10) DEFAULT NULL,
  `CONFIRMED` char(1) DEFAULT NULL,
  `NEXT_AVAILABLE` date DEFAULT NULL,
  `RESUME_SUBMITTED` enum('0','1') NOT NULL DEFAULT '0' COMMENT '0: false , 1: true',
  `EXPERIENCE_ID` text
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



# Dump of table PROJECT_STATUS
# ------------------------------------------------------------

DROP TABLE IF EXISTS `PROJECT_STATUS`;

CREATE TABLE `PROJECT_STATUS` (
  `STATUS_ID` int(10) NOT NULL,
  `STATUS_NAME` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



# Dump of table PROJECT_TYPE
# ------------------------------------------------------------

DROP TABLE IF EXISTS `PROJECT_TYPE`;

CREATE TABLE `PROJECT_TYPE` (
  `TYPE_ID` int(10) NOT NULL,
  `TYPE_NAME` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



# Dump of table REGION
# ------------------------------------------------------------

DROP TABLE IF EXISTS `REGION`;

CREATE TABLE `REGION` (
  `REGION_ID` int(10) NOT NULL,
  `REGION_NAME` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



# Dump of table ROLE
# ------------------------------------------------------------

DROP TABLE IF EXISTS `ROLE`;

CREATE TABLE `ROLE` (
  `ID` int(11) NOT NULL,
  `ROLE_NAME` varchar(255) NOT NULL,
  `COMBINATION_ID` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



# Dump of table STAFF
# ------------------------------------------------------------

DROP TABLE IF EXISTS `STAFF`;

CREATE TABLE `STAFF` (
  `STAFF_ID` varchar(255) NOT NULL,
  `FIRST_NAME` varchar(255) NOT NULL,
  `MIDDLE_INITIAL` varchar(255) DEFAULT NULL,
  `LAST_NAME` varchar(255) NOT NULL,
  `PREFERRED_NAME` varchar(255) DEFAULT NULL,
  `EMAIL_ID` varchar(255) DEFAULT NULL,
  `PHONE_1` varchar(255) DEFAULT NULL,
  `PHONE_1_TYPE` varchar(255) DEFAULT NULL,
  `PHONE_2` varchar(255) DEFAULT NULL,
  `PHONE_2_TYPE` varchar(255) DEFAULT NULL,
  `HOME_CITY` varchar(255) DEFAULT NULL,
  `HOME_STATE` varchar(255) DEFAULT NULL,
  `HOME_ZIP` varchar(255) DEFAULT NULL,
  `STAFF_CERTIFICATION` char(1) DEFAULT 'N',
  `STAFF_TRAINING` char(1) DEFAULT 'N',
  `STAFF_PHOTO` varchar(255) DEFAULT NULL,
  `STAFF_ROLE_ID` int(10) DEFAULT NULL,
  `STAFF_GROUP_ID` int(10) DEFAULT NULL,
  `STAFF_STATUS_ID` int(10) DEFAULT NULL,
  `OFFICE_ID` varchar(255) DEFAULT NULL,
  `EMPLOYMENT_START_DATE` date DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



# Dump of table STAFF_CERTIFICATION
# ------------------------------------------------------------

DROP TABLE IF EXISTS `STAFF_CERTIFICATION`;

CREATE TABLE `STAFF_CERTIFICATION` (
  `STAFF_ID` varchar(255) NOT NULL,
  `CERTIFICATION_ID` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



# Dump of table STAFF_EXPERIENCE
# ------------------------------------------------------------

DROP TABLE IF EXISTS `STAFF_EXPERIENCE`;

CREATE TABLE `STAFF_EXPERIENCE` (
  `EXPERIENCE_ID` int(11) NOT NULL,
  `EXPERIENCE_LABEL` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



# Dump of table STAFF_GROUP
# ------------------------------------------------------------

DROP TABLE IF EXISTS `STAFF_GROUP`;

CREATE TABLE `STAFF_GROUP` (
  `GROUP_ID` int(10) NOT NULL,
  `GROUP_NAME` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



# Dump of table STAFF_ROLE
# ------------------------------------------------------------

DROP TABLE IF EXISTS `STAFF_ROLE`;

CREATE TABLE `STAFF_ROLE` (
  `ROLE_ID` int(10) NOT NULL,
  `ROLE_NAME` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



# Dump of table STAFF_STATUS
# ------------------------------------------------------------

DROP TABLE IF EXISTS `STAFF_STATUS`;

CREATE TABLE `STAFF_STATUS` (
  `STATUS_ID` int(10) NOT NULL,
  `STATUS_NAME` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



# Dump of table USER_ACCESS
# ------------------------------------------------------------

DROP TABLE IF EXISTS `USER_ACCESS`;

CREATE TABLE `USER_ACCESS` (
  `ID` int(11) NOT NULL,
  `USER_ID` int(11) NOT NULL,
  `OFFICE_ID` varchar(255) DEFAULT NULL,
  `REGION_ID` int(11) NOT NULL,
  `DIVISION_ID` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



# Dump of table USERS
# ------------------------------------------------------------

DROP TABLE IF EXISTS `USERS`;

CREATE TABLE `USERS` (
  `ID` int(11) NOT NULL,
  `ROLE_ID` int(11) NOT NULL,
  `FIRST_NAME` varchar(45) NOT NULL,
  `MIDDLE_NAME` varchar(45) NOT NULL,
  `LAST_NAME` varchar(45) NOT NULL,
  `EMAIL` varchar(155) NOT NULL,
  `PASSWORD` varchar(255) NOT NULL,
  `VERIFIED` enum('true','false') NOT NULL,
  `ADDRESS` varchar(255) NOT NULL,
  `CITY` varchar(100) NOT NULL,
  `COUNTRY` varchar(255) NOT NULL,
  `ZIP` varchar(255) NOT NULL,
  `SUBSCRIPTION_SERVICE_ID` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;




/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
