module.exports = {
  fetchCompany: (environment, domain) => (
    `SELECT
        COMPANY.* 
    FROM COMPANY
    INNER JOIN COMPANY_ENVIRONMENT
      ON COMPANY.ID = COMPANY_ENVIRONMENT.COMPANY_ID
    INNER JOIN ENVIRONMENT_TYPE
      ON ENVIRONMENT_TYPE.ID = COMPANY_ENVIRONMENT.ENVIRONMENT_TYPE_ID
    WHERE
      ENVIRONMENT_TYPE.SUBDOMAIN = '${environment}'
    AND 
      COMPANY.DOMAIN = '${domain}'`
  ),
  validate: (username, password) => (
    `SELECT  USERS.*, ROLE.ROLE_NAME, ROLE.COMBINATION_ID 
      FROM USERS INNER JOIN ROLE ON USERS.ROLE_ID = ROLE.ID 
      WHERE EMAIL = '${username}' AND PASSWORD = '${password}'`
  ),
  office: (userId) => (
    `SELECT USER_ACCESS.OFFICE_ID, OFFICE.OFFICE_NAME FROM USER_ACCESS
      INNER JOIN OFFICE ON OFFICE.OFFICE_ID = USER_ACCESS.OFFICE_ID
      WHERE USER_ACCESS.USER_ID = ${userId}`
  )
}
