module.exports = {
  customerList: () => (
    ` 
    SELECT
      CUSTOMER_ID,
      CUSTOMER_NAME     
    FROM 
      CUSTOMER
    `
  ),
  getCustomerContactsById: (id) => (
    `
    SELECT
      CUSTOMER_CONTACTS.CONTACT_ID,
      CONTACT.NAME CONTACT_NAME
    FROM 
      CUSTOMER_CONTACTS
    INNER JOIN CUSTOMER
      ON CUSTOMER_CONTACTS.CUSTOMER_ID=CUSTOMER.CUSTOMER_ID
    INNER JOIN CONTACT
      ON CUSTOMER_CONTACTS.CONTACT_ID=CONTACT.CONTACT_ID 
    WHERE
      CUSTOMER.CUSTOMER_ID = ${id}
    `
  )
}